name: run hello.py

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
<<<<<<< HEAD
        run: python hello.py
=======
        run: python hello.py
>>>>>>> 25fdca61110ad250a4da1886ec4c83a675235d2b
